# Generated by Django 3.1.2 on 2020-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MN', 'Man'), ('WM', 'Women')], max_length=2, null=True),
        ),
    ]
