# Generated by Django 3.1.2 on 2020-10-23 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripAccomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TripActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('AD', 'Biking'), ('WN', 'Hiking'), ('CT', 'Running')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('AD', 'Adventure'), ('WN', 'Wildlife & Nature'), ('CT', 'Cities'), ('RU', 'Ruins & temples'), ('RT', 'Road trips'), ('HK', 'Hiking'), ('FD', 'Food & drink'), ('AC', 'Art & culture'), ('CI', 'Coasts & islans'), ('FA', 'Family')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TripTrasnsfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('rivable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trip.rivable')),
                ('api_id', models.CharField(max_length=100)),
            ],
            bases=('trip.rivable',),
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('rivable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trip.rivable')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=50)),
            ],
            bases=('trip.rivable',),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('stars', models.IntegerField()),
                ('helpful', models.PositiveIntegerField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rivable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.rivable')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Places')),
                ('default_image', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='trip.rivable')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('rivable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trip.rivable')),
                ('subject', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geo_json', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson', 'gpx'])])),
                ('activities', models.ManyToManyField(to='trip.TripActivities')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='trip.TripCategory')),
            ],
            bases=('trip.rivable',),
        ),
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.trip')),
            ],
        ),
    ]
