# Generated by Django 3.1.2 on 2020-11-01 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.rivable'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='trip.rivable'),
        ),
        migrations.AddField(
            model_name='companions',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(to='trip.TripActivities'),
        ),
        migrations.AddField(
            model_name='trip',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(to='trip.TripCategory'),
        ),
        migrations.AddField(
            model_name='companions',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.trip'),
        ),
    ]
