# Generated by Django 3.1.2 on 2020-11-03 09:22

from django.db import migrations, models
import django.db.models.deletion
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20201101_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='api_id',
        ),
        migrations.AddField(
            model_name='images',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='images',
            name='latitud',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='longitud',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tripplaces',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.places'),
        ),
        migrations.AddField(
            model_name='tripplaces',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.trip'),
        ),
    ]
