# Generated by Django 3.1.2 on 2020-11-03 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20201103_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='activities',
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.tripactivities'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.tripcategory'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='geo_json',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson', 'gpx'])]),
        ),
    ]
