# Generated by Django 3.1.2 on 2020-11-03 10:16

from django.db import migrations, models
import django.db.models.deletion
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20201103_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Places')),
                ('default_image', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('latitud', models.CharField(editable=False, max_length=20, null=True)),
                ('longitud', models.CharField(editable=False, max_length=20, null=True)),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('rivable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='trip.rivable')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
