# Generated by Django 3.1.2 on 2020-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20201103_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='activities',
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(to='trip.TripActivities'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(to='trip.TripCategory'),
        ),
    ]
