# Generated by Django 3.1.2 on 2020-11-03 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0006_auto_20201103_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.CreateModel(
            name='UserLinked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_trips', models.ManyToManyField(blank=True, related_name='likedtrips', to='trip.Trip')),
                ('saved_places', models.ManyToManyField(blank=True, related_name='savedplaces', to='trip.Place')),
                ('saved_trips', models.ManyToManyField(blank=True, related_name='savedtrips', to='trip.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
