# Generated by Django 3.1.2 on 2020-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20201103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(blank=True, to='trip.TripActivities'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(blank=True, to='trip.TripCategory'),
        ),
        migrations.AlterField(
            model_name='tripactivities',
            name='title',
            field=models.CharField(choices=[('AD', 'Biking'), ('WN', 'Hiking'), ('CT', 'Running')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tripcategory',
            name='title',
            field=models.CharField(choices=[('AD', 'Adventure'), ('WN', 'Wildlife & Nature'), ('CT', 'Cities'), ('RU', 'Ruins & temples'), ('RT', 'Road trips'), ('HK', 'Hiking'), ('FD', 'Food & drink'), ('AC', 'Art & culture'), ('CI', 'Coasts & islans'), ('FA', 'Family')], default=None, max_length=2, null=True),
        ),
    ]
