# Generated by Django 3.1.2 on 2020-11-03 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_auto_20201103_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful',
        ),
        migrations.AddField(
            model_name='review',
            name='helpfull',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
