# Generated by Django 3.1.2 on 2020-11-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_auto_20201111_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
